name: Build and Push Docker Image

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  REGISTRY_NAME: tanzilakhalfan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract repository name
      id: vars
      run: echo "REPO_NAME=$(echo ${{ github.repository }} | awk -F '/' '{print $2}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # You can use a static value like 'username'
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build Docker image
      run: |
        docker build -t ${{ env.REGISTRY_NAME }}/${{ env.REPO_NAME }}:${{ github.run_id }} .

    - name: Push Docker image to registry
      run: |
        docker push ${{ env.REGISTRY_NAME }}/${{ env.REPO_NAME }}:${{ github.run_id }}

        #for