name: Build and Push Docker Image

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  REGISTRY_NAME: tanzilakhalfan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract repository name
      id: vars
      run: echo "REPO_NAME=$(echo ${{ github.repository }} | awk -F '/' '{print $2}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest requests

    - name: Lint code
      run: |
        flake8 .

    - name: Run tests
      run: |
        python -m unittest discover -s app/unit-tests -p "test_*.py"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build Docker image
      run: |
        docker build -t ${{ env.REGISTRY_NAME }}/${{ env.REPO_NAME }}:${{ github.run_number }} .

    - name: Push Docker image to registry
      run: |
        docker push ${{ env.REGISTRY_NAME }}/${{ env.REPO_NAME }}:${{ github.run_number }}
    
    - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GIT_HUB_TOKEN }}"